server:
    port: 8287
    servlet:
        contextPath: /node-name

spring:
    servlet:
        multipart:
            max-file-size: -1
            max-request-size: -1
            enabled: true
    autoconfigure:
        exclude:
          - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
          - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

klab:
    log:
        file: /home/klab/.klab/logs/klab.log.0
    node:
        submitting: "*"
        searching: "*"
    adapter:
        copernicus:
            static:
                auth: "*"
            auth: "*"
    geoserver:
        url: http://geoserver:8080/geoserver
        user: admin
        password: password
    postgres:
        host: postgres
        password: password
        port: 5432
        user: postgres
    copernicus:
        cds:
            user: copernicus-user
            apikey: copernicus-api-key

logging:
    file:
        name: /home/klab/.klab/logs/klab.log
